### PR TITLE
OSU Process Trees

### PR DESCRIPTION
**Pull request by carriganm95**
Added directory with scripts to process offline trees using singularity and condor on the OSU T3.

### CODE REVIEW

**Comment by mcitron** [comment]
I think this is fine but would but good to change the directory to "processTrees/OSU" to make clear what this is for. It would also be good to make use of the mongoDB framework to keep track of files as done here: https://github.com/carriganm95/milliqanOffline/blob/processTreesOSU/Run3Detector/scripts/processRuns.py

**Comment by mcitron** [comment]
hey, any updates here?

**Comment by carriganm95** [comment]
> hey, any updates here?

no sorry busy at p5. Probably won't have time until I am back in the US next week.

**Comment by carriganm95** [comment]
Ok this should be good now. I have turned on publish and added a utilities file that will help us to change the publication location. When the files are created on our compute nodes the location is not permanent.

**Pull request merged**
