### PR TITLE
Add Bool to For Board Matching

### PR DESCRIPTION
**Pull request by carriganm95**
This PR adds a bool to the offline trees to check if all digitizers in an event are matched. The TDC time of each board is used to test if the digitizer info is present in an event. If one digitizer or more is missing from an event the bool boardsMatched is set to false.

### CODE REVIEW

**Comment by mcitron** [comment]
The board matching looks good but also seems to be some other unrelated files added. What are these for?

**Comment by carriganm95** [comment]
I'll remove those. They are scripts I had pushed for other people here at OSU to have examples.

**Comment by mcitron** [comment]
Ok, I made a PR that adds a directory called "analysis" with sub directories for things like dark rate measurement. Could put them there?

**Comment by carriganm95** [comment]
This is fixed now. I am planning to incorporate the checkTriggers script into the offline trees. I think it would be good to have info on which triggers should have fired available. The other script was just a modified version of David's script so I don't think it is very useful. I have left them out for now.

**Pull request merged**
