### PR TITLE
v33 Offline Trees

### PR DESCRIPTION
**Pull request by carriganm95**
Adds new map for runs 1102 and onward (moved panel channels)

runOfflineFactory.py will now pick up the correct mapping from configuration/runInfo.json

new spe calibrations in configuration/calibrations/supermodulesCalibrationAug23.json

### CODE REVIEW

**Comment by mcitron** [comment]
Nice updates! Two quick suggestions -

1) name configs based on run ranges rather than dates? I think this would be clearer
2) also swap SPE and timing calibrations to the correct channels for the relevant eras (this should be fine as the only change is the channel used in the digi I believe)

**Comment by carriganm95** [comment]
> Nice updates! Two quick suggestions -
> 
> 1. name configs based on run ranges rather than dates? I think this would be clearer
> 2. also swap SPE and timing calibrations to the correct channels for the relevant eras (this should be fine as the only change is the channel used in the digi I believe)

yes that is a good idea. If it's ok with people I would propose having just one config for channel maps and calibrations then. it would simplify things

**Comment by carriganm95** [comment]
all changes should be made now. I tested for both slab and bar detector and everything looks good

**Comment by carriganm95** [comment]
timing configuration data is now added to the configs. This should be ready for merge if someone can take a last look

**Comment by ssantpur** [comment]
Channel map reads [-1,-1,-1,-1],[-1,-1,-1,-1] for both channels 78 and 79 which are now 24 and 25. Is this expected to be same? From event displays perspective, it might be nice to have them unique so that these can be assigned to 24 and 25 appropriately. Note that [-1,-1,-1,-1] is used for many channels in the panel digitizer.

**Comment by carriganm95** [comment]
> Channel map reads [-1,-1,-1,-1],[-1,-1,-1,-1] for both channels 78 and 79 which are now 24 and 25. Is this expected to be same? From event displays perspective, it might be nice to have them unique so that these can be assigned to 24 and 25 appropriately. Note that [-1,-1,-1,-1] is used for many channels in the panel digitizer.

For runs with the channel swap the configs have actual values for 78/79. It is only pre 24/25 swap that they are set to -1. They are unused so I think this makes sense but we could use an index to number them if it helps somewhere. May just cause confusion to label unused channels.

**Comment by ssantpur** [comment]
I see. The changes look good to me. Can be merged if there are no further comments.

**Pull request merged**
